# Generated by Django 5.0.6 on 2024-06-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationtype',
            old_name='preference_type',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='notificationtype',
            unique_together={('preference', 'type')},
        ),
    ]
