# Generated by Django 5.0.6 on 2024-06-30 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notificationtype_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noti_prefs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
